version: "3.8"

services:
  python-service:
    build: .
    container_name: python-service
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - ecommerce-network
    volumes:
      - pip_cache:/root/.cache/pip
      - hf_cache:/root/.cache/huggingface

networks:
  ecommerce-network:
    driver: bridge

volumes:
  pip_cache:
  hf_cache: # Volume cache HF
