spring:
  application:
    name: ecommerce

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

dlk:
  jwt:
    base64-secret: ${JWT_SECRET}
    access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY}
    refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY}

  upload-file:
    base-uri: ${UPLOAD_FILE_PATH}

ghn:
  api-url: ${GHN_API_URL}
  token: ${GHN_TOKEN}
